# Regenerate validation/sd-golden.json — the reference numbers the Stable
# Diffusion checks compare against.
#
# Run rarely: only when a checkpoint changes, or to re-confirm against a newer
# diffusers. The output is committed, so nobody else needs any of this
# installed — the checks it feeds run with nothing but mlx-ts and cached weights.
#
# These are PyTorch: diffusers and transformers, the implementations these
# checkpoints were published for. Not mlx-examples, which is a port like ours;
# comparing two ports can only show they agree. (Spark-TTS is the cautionary
# tale — we matched another MLX port exactly and were both wrong.)
#
# Fingerprints are emitted in *our* channels-last layout, so first4 compares
# directly rather than only mean and absmean.
#
#   /tmp/sdvenv/bin/pip install torch diffusers transformers
#   /tmp/sdvenv/bin/python reference/gen-sd-fixtures.py
import json
import os

import torch

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "validation", "sd-golden.json")

# The same deterministic fill validation/*.ts uses.
def det(n, seed):
    return torch.tensor([((i * 131 + seed * 977 + 7) % 1009) / 1009 - 0.5 for i in range(n)],
                        dtype=torch.float32)


def stats(a):
    f = a.flatten().float()
    return {"shape": list(a.shape), "sum": round(float(f.sum()), 4),
            "mean": round(float(f.mean()), 8), "absmean": round(float(f.abs().mean()), 8),
            "first4": [round(float(v), 8) for v in f[:4]]}


golden = {"_": "Generated by reference/gen-sd-fixtures.py from PyTorch diffusers "
               "and transformers. Fingerprints are in channels-last layout, to "
               "match ours. Do not hand-edit."}

# ---- CLIP tokenizer -------------------------------------------------------
from transformers import CLIPTokenizer

CASES = ["a photo of a cat", "A  PHOTO   of a CAT", "uplifting trance, 138 bpm",
         "an astronaut riding a horse on mars, highly detailed, 4k",
         "hello-world (test) 42", "it's a dog's life", "cafe naive"]
ctok = CLIPTokenizer.from_pretrained("openai/clip-vit-large-patch14")
golden["clip_tokenizer"] = {"cases": CASES,
                            "ids": [list(ctok(c)["input_ids"]) for c in CASES]}

# ---- CLIP text encoder ----------------------------------------------------
from transformers import CLIPTextModel

IDS = [49406, 320, 1125, 539, 320, 2368, 49407, 49407, 49407, 49407]
tm = CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14", dtype=torch.float32).eval()
with torch.no_grad():
    # SD conditions on the last hidden state, after the final layer norm.
    golden["clip_text"] = {"ids": IDS, **stats(tm(torch.tensor([IDS])).last_hidden_state)}
del tm

# ---- VAE decoder ----------------------------------------------------------
from diffusers import AutoencoderKL

vae = AutoencoderKL.from_pretrained("stabilityai/sd-vae-ft-mse", dtype=torch.float32).eval()
B, h, w = 1, 16, 16
C = vae.config.latent_channels
z = det(B * h * w * C, 1).reshape(B, h, w, C).permute(0, 3, 1, 2).contiguous()
with torch.no_grad():
    img = vae.decode(z / vae.config.scaling_factor).sample
golden["vae"] = {"latent": [B, h, w, C], "seed": 1,
                 **stats(img.permute(0, 2, 3, 1).contiguous())}   # -> channels-last
del vae

# ---- UNet -----------------------------------------------------------------
from diffusers import UNet2DConditionModel

unet = UNet2DConditionModel.from_pretrained(
    "stable-diffusion-v1-5/stable-diffusion-v1-5", subfolder="unet", dtype=torch.float32).eval()
H = W = 16
C, D = unet.config.in_channels, unet.config.cross_attention_dim
x = det(B * H * W * C, 1).reshape(B, H, W, C).permute(0, 3, 1, 2).contiguous()
cond = det(B * 77 * D, 2).reshape(B, 77, D)
with torch.no_grad():
    out = unet(x, torch.tensor(500.0), encoder_hidden_states=cond).sample
golden["unet"] = {"latent": [B, H, W, C], "cond": [B, 77, D], "timestep": 500,
                  **stats(out.permute(0, 2, 3, 1).contiguous())}
del unet

# ---- noise schedule -------------------------------------------------------
from diffusers import EulerDiscreteScheduler

s = EulerDiscreteScheduler(beta_start=0.00085, beta_end=0.012,
                           beta_schedule="scaled_linear", num_train_timesteps=1000)
sig = ((1 - s.alphas_cumprod) / s.alphas_cumprod) ** 0.5
# Ours reparametrises to continuous time: sigma(0) = 0 and sigma(t) = sig[t-1]
# at integer t, interpolating between. Store the raw curve and let the TS side
# assert that mapping.
golden["scheduler"] = {
    "betas": {"beta_start": 0.00085, "beta_end": 0.012, "schedule": "scaled_linear",
              "num_train_timesteps": 1000},
    "sigmas_len": len(sig),
    "first4": [round(float(v), 8) for v in sig[:4]],
    "last3": [round(float(v), 8) for v in sig[-3:]],
    "at": {str(t): round(float(sig[t - 1]), 8) for t in (1, 12, 13, 500, 999, 1000)},
}

with open(OUT, "w") as f:
    json.dump(golden, f, indent=2)
    f.write("\n")
print("wrote", OUT)
