# Regenerate validation/spark-golden.json — the reference numbers the Spark
# checks compare against.
#
# Run rarely: only when the checkpoint changes, or to re-confirm the numbers
# against a newer PyTorch. The output is committed, so nobody else needs any of
# this installed. That is the point — the checks it feeds run with nothing but
# mlx-ts and a cached checkpoint.
#
# These are the ORIGINAL PyTorch Spark-TTS and Hugging Face's own Qwen2, not
# another MLX port. Comparing one port against another can only show they agree,
# and the port that was used first turned out to be wrong three times over: a
# left-aligned STFT window where torch.stft centres it, `groups` passed
# positionally into conv_transpose1d's `output_padding` slot, and never leaving
# training mode. The first two changed our numbers.
#
# Setup — Spark-TTS is not on PyPI, so its modules have to be fetched:
#
#   /tmp/sdvenv/bin/pip install torch torchaudio transformers tokenizers \
#     einops einx omegaconf soundfile safetensors
#   mkdir -p /tmp/sparktts/sparktts/{models,modules/{blocks,encoder_decoder,speaker,fsq,vq},utils}
#   cd /tmp/sparktts && find sparktts -type d -exec touch {}/__init__.py \;
#   B=https://raw.githubusercontent.com/SparkAudio/Spark-TTS/main/sparktts
#   for f in models/bicodec.py modules/blocks/layers.py modules/blocks/samper.py \
#            modules/blocks/vocos.py modules/encoder_decoder/feat_decoder.py \
#            modules/encoder_decoder/feat_encoder.py modules/encoder_decoder/wave_generator.py \
#            modules/fsq/finite_scalar_quantization.py modules/fsq/residual_fsq.py \
#            modules/speaker/ecapa_tdnn.py modules/speaker/perceiver_encoder.py \
#            modules/speaker/speaker_encoder.py modules/speaker/pooling_layers.py \
#            modules/vq/factorized_vector_quantize.py utils/file.py; do
#     curl -sL "$B/$f" -o "sparktts/$f"; done
#
#   MLX_SPARK=/tmp/sparktts /tmp/sdvenv/bin/python reference/gen-spark-fixtures.py
import json
import os
import sys

sys.path.insert(0, os.environ.get("MLX_SPARK", "/tmp/sparktts"))

import torch
import torchaudio.transforms as TT
from safetensors.torch import load_file
from sparktts.models.bicodec import BiCodec
from sparktts.modules.speaker.speaker_encoder import SpeakerEncoder
from tokenizers import Tokenizer
from transformers import Qwen2ForCausalLM

ROOT = os.path.expanduser("~/.cache/mlx-ts/mlx-community/Spark-TTS-0.5B-bf16")
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "validation", "spark-golden.json")


def stats(a):
    f = a.flatten().float()
    return {"shape": list(a.shape), "mean": round(float(f.mean()), 8),
            "absmean": round(float(f.abs().mean()), 8),
            "first4": [round(float(v), 8) for v in f[:4]]}


golden = {
    "_": "Generated by reference/gen-spark-fixtures.py from the original PyTorch "
         "Spark-TTS and Hugging Face Qwen2. Do not hand-edit.",
}

# ---- BiCodec decode: quantizer -> speaker FSQ -> prenet -> wave generator ----
bicodec = BiCodec.load_from_checkpoint(f"{ROOT}/BiCodec")
bicodec.eval()
T = 16
semantic = torch.tensor([[(i * 137 + 11) % 8192 for i in range(T)]], dtype=torch.long)
glob = torch.tensor([[(i * 91 + 7) % 4096 for i in range(32)]], dtype=torch.long).unsqueeze(1)
with torch.no_grad():
    z_q = bicodec.quantizer.detokenize(semantic)
    d_vector = bicodec.speaker_encoder.detokenize(glob)
    prenet = bicodec.prenet(z_q, d_vector)
    wav = bicodec.decoder(prenet + d_vector.unsqueeze(-1))
golden["bicodec"] = {"semantic": semantic.flatten().tolist(),
                     "global": glob.flatten().tolist(),
                     "z_q": stats(z_q), "d_vector": stats(d_vector),
                     "prenet": stats(prenet), "wav": stats(wav)}

# ---- speaker encoder: mel -> ECAPA -> perceiver -> FSQ -> 32 tokens ----
sd = {k[len("speaker_encoder."):]: v.float()
      for k, v in load_file(f"{ROOT}/BiCodec/model.safetensors").items()
      if k.startswith("speaker_encoder.")}
spk = SpeakerEncoder(input_dim=128, out_dim=1024, latent_dim=128, token_num=32,
                     fsq_levels=[4, 4, 4, 4, 4, 4], fsq_num_quantizers=1)
spk.load_state_dict(sd, strict=True)
spk.eval()
N = 6 * 16000 // 320 * 320
ref_wav = torch.tensor([((i * 131 + 7) % 1009) / 1009 - 0.5 for i in range(N)], dtype=torch.float32)
# Built exactly as BiCodec.init_mel_transformer does.
mel_fn = TT.MelSpectrogram(16000, 1024, 640, 320, 10, None,
                           n_mels=128, power=1, norm="slaney", mel_scale="slaney")
with torch.no_grad():
    mel = mel_fn(ref_wav[None, ...]).squeeze(1).transpose(1, 2)
    x_vector, features = spk.speaker_encoder(mel, True)
    latents = spk.perceiver_sampler(features.transpose(1, 2))
    tokens = spk.tokenize(mel).flatten().tolist()
golden["speaker"] = {"samples": N, "mel": stats(mel), "features": stats(features),
                     "x_vector": stats(x_vector), "latents": stats(latents),
                     "tokens": tokens}

# ---- the LM, at float32 so the comparison is exact rather than a ranking ----
TEXT = "MLX runs on the GPU of your Mac."
prompt_str = ("<|task_controllable_tts|><|start_content|>" + TEXT + "<|end_content|>"
              "<|start_style_label|><|gender_0|><|pitch_label_2|><|speed_label_2|><|end_style_label|>")
ids = Tokenizer.from_file(f"{ROOT}/tokenizer.json").encode(prompt_str, add_special_tokens=False).ids
lm = Qwen2ForCausalLM.from_pretrained(ROOT, dtype=torch.float32)
lm.eval()
with torch.no_grad():
    last = lm(torch.tensor([ids])).logits[0, -1]
    top = last.topk(5)
    cur, gen = list(ids), []
    for _ in range(16):
        nxt = int(lm(torch.tensor([cur])).logits[0, -1].argmax())
        gen.append(nxt)
        cur.append(nxt)
golden["lm"] = {"text": TEXT, "prompt_ids": list(ids),
                "top5": [[int(i), round(float(v), 6)] for v, i in zip(top.values, top.indices)],
                "greedy_ids": gen}

with open(OUT, "w") as f:
    json.dump(golden, f, indent=2)
    f.write("\n")
print("wrote", OUT)
