# Regenerate validation/parakeet-golden.json — the reference numbers the Parakeet
# checks compare against.
#
# Run rarely: only when the checkpoint changes, or to re-confirm against a newer
# transformers. The output is committed, so nobody else needs any of this
# installed — the checks it feeds run with nothing but mlx-ts and a cached
# checkpoint.
#
# The reference is `transformers.ParakeetForTDT`, the implementation NVIDIA
# published these weights for. Not an MLX port: comparing two ports can only
# show they agree, which is how a wrong STFT window nearly shipped in the
# Spark-TTS speaker encoder.
#
#   /tmp/sdvenv/bin/pip install torch transformers librosa
#   /tmp/sdvenv/bin/python reference/gen-parakeet-fixtures.py
import json
import os

import numpy as np
import torch
from transformers import ParakeetForTDT
from transformers.models.parakeet.feature_extraction_parakeet import ParakeetFeatureExtractor

REPO = "nvidia/parakeet-tdt-0.6b-v3"
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "validation", "parakeet-golden.json")

# Deterministic synthetic audio: no fixture file, and the token ids it produces
# are as good a check of the decode path as real speech would be.
SECONDS = 2
N = 16000 * SECONDS
wav = np.array([((i * 131 + 7) % 1009) / 1009 - 0.5 for i in range(N)], dtype=np.float32)


def stats(a):
    f = a.flatten().float()
    return {"shape": list(a.shape), "mean": round(float(f.mean()), 8),
            "absmean": round(float(f.abs().mean()), 8),
            "first4": [round(float(v), 8) for v in f[:4]]}


model = ParakeetForTDT.from_pretrained(REPO, dtype=torch.float32).eval()
fe = ParakeetFeatureExtractor(feature_size=128, sampling_rate=16000, hop_length=160,
                              n_fft=512, win_length=400, preemphasis=0.97)
feats = fe(wav, sampling_rate=16000, return_tensors="pt")

golden = {"_": "Generated by reference/gen-parakeet-fixtures.py from PyTorch "
               "transformers.ParakeetForTDT. Do not hand-edit.",
          "seconds": SECONDS}

with torch.no_grad():
    mel = feats.input_features
    golden["mel"] = stats(mel)

    enc = model.encoder
    sub = enc.subsampling(mel)
    if isinstance(sub, tuple):
        sub = sub[0]
    golden["subsample"] = stats(sub)
    golden["pos_embed"] = stats(enc.encode_positions(sub))

    hidden = enc(mel)
    hidden = hidden.last_hidden_state if hasattr(hidden, "last_hidden_state") else hidden[0]
    golden["encoder"] = stats(hidden)
    golden["encoder_projected"] = stats(model.encoder_projector(hidden))

# Deliberately no token fixture. On synthetic noise the model is maximally
# uncertain — the blank logit ties the best real token to four decimals
# (-0.1904 for both at frame 0) — so the argmax is a coin flip and the decode
# trajectory diverges for reasons that say nothing about the implementation.
# The transcript is checked on real speech instead, by
# validation/parakeet-transcribe.ts, which needs no audio fixture: Spark-TTS
# speaks a sentence and Parakeet reads it back.

with open(OUT, "w") as f:
    json.dump(golden, f, indent=2)
    f.write("\n")
print("wrote", OUT)
